config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  get '/vacancies' => 'vacancies#index', as: :company_root
  resources :applicants
  resources :vacancies
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :vacancy

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vacancies

  validates :name, presence: true
  validates :description, length: {minimum:3, maximum:1000},
            presence: true
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :company
  has_many :applicants

  validates :title, presence: true
  validates :location, presence: true
  validates :description, length: {minimum:3, maximum:1000},
            presence: true
  validates :requirements, presence: true
  validates :salary, presence: true
  
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: %i[ show edit update destroy ]

  # GET /applicants or /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1 or /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants or /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: "Applicant was successfully created." }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1 or /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: "Applicant was successfully updated." }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1 or /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: "Applicant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def applicant_params
      params.require(:applicant).permit(:name, :vacancy_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_company!
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name description])
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  # GET /companies or /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i[ show edit update destroy ]

  # GET /vacancies or /vacancies.json
  def index
    @vacancies = Vacancy.all
  end

  # GET /vacancies/1 or /vacancies/1.json
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new(available: true)
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies or /vacancies.json
  def create
    @vacancy = current_company.vacancies.build(vacancy_params)

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: "A vaga foi criada com sucesso." }
        format.json { render :show, status: :created, location: @vacancy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacancies/1 or /vacancies/1.json
  def update
    respond_to do |format|
      if @vacancy.update(vacancy_params)
        format.html { redirect_to @vacancy, notice: "Vacancy was successfully updated." }
        format.json { render :show, status: :ok, location: @vacancy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1 or /vacancies/1.json
  def destroy
    @vacancy.destroy
    respond_to do |format|
      format.html { redirect_to vacancies_url, notice: "Vacancy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vacancy_params
      params.require(:vacancy).permit(:title, :location, :description, :requirements, :salary, :available, :company_id)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/applicants/_form.html.erb
<%= form_with(model: applicant, local: true) do |form| %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
        <% applicant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :vacancy_id %>
    <%= form.text_field :vacancy_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applicants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vacancy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= applicant.name %></td>
        <td><%= applicant.vacancy_id %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applicant.name %>
</p>

<p>
  <strong>Vacancy:</strong>
  <%= @applicant.vacancy_id %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onebitjobs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<html>
  <head>
    <title>Onebitjobs</title>
    <meta name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5 ">
  <div class="container container-fluid">
    <a class="navbar-brand" href="/vacancies/all">
      <img class="navbar-brand" src="/assets/onebitjobs.png" class='img-fluid' alt="Onebitjobs logo" height="45" />
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item ">
          <a class="nav-link text-white" href="/vacancies/all">Vagas</a>
        </li>
        <% unless company_signed_in? %>
          <li class="nav-item">
            <a class="nav-link text-white" href="/companies/sign_up">Anunciar</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link text-white" href="/vacancies/new">Anunciar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="/vacancies">Meus Anúncios</a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
          <% if company_signed_in? %>
            <li class="nav-item">
              <%= link_to('Sair', destroy_company_session_path, method: :delete, class: 'nav-link') %>
            </li>
          <% else %>
            <li class="nav-item">
                <a class="nav-link text-white" href="/companies/sign_in">Entrar</a>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/vacancies/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: vacancy) do |form| %>
      <% if vacancy.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

          <ul>
            <% vacancy.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
        <%= form.label 'Título', class: 'form-label' %>

        <%= form.text_field :title, autofocus: true, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Local', class: 'form-label' %>

        <%= form.text_field :location, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Descrição', class: 'form-label' %>

        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Requisitos', class: 'form-label' %>

        <%= form.text_area :requirements, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.label 'Salário', class: 'form-label' %>

        <%= form.text_field :salary, class: 'form-control' %>
      </div>
      <div class="mb-4">
        <%= form.check_box :available, class: 'form-check-input', id: 'availableCheck' %>
        <%= form.label 'Disponível', class: "form-check-label", for: "availableCheck" %>

      </div>
      <div class="mb-4 mt-5">
        <%= form.submit "Salvar", class: "btn btn-danger bg-site-red" %>
      </div>
    <% end %>
  </div>
</div>

app/views/vacancies/edit.html.erb
<div class="container">
  <h1>Editar Anúncio</h1>

  <%= render 'form', vacancy: @vacancy %>
</div>

app/views/vacancies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacancies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th>Requirements</th>
      <th>Salary</th>
      <th>Available</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.title %></td>
        <td><%= vacancy.location %></td>
        <td><%= vacancy.description %></td>
        <td><%= vacancy.requirements %></td>
        <td><%= vacancy.salary %></td>
        <td><%= vacancy.available %></td>
        <td><%= vacancy.company_id %></td>
        <td><%= link_to 'Show', vacancy %></td>
        <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<div class="container">
  <h1>Nova vaga</h1>

  <%= render 'form', vacancy: @vacancy %>
</div>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @vacancy.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @vacancy.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vacancy.description %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @vacancy.requirements %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @vacancy.salary %>
</p>

<p>
  <strong>Available:</strong>
  <%= @vacancy.available %>
</p>

<p>
  <strong>Company:</strong>
  <%= @vacancy.company_id %>
</p>

<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>